/*
 *创建头文件: HelloJNI.h, 可以通过javah自动生成: javah HelloJNI
 *java中定义的sayHello()方法，在头文件中生成了
 *JNIEXPORT void JNICALL Java_HelloJNI_sayHello(JNIEnv *, jobject)方法
 *其格式可以概括为: JNIWXPORT <返回类型> JNICALL Java_<包名>_<类名>_<方法名>(JNIEnv *, jobject, <参数>); 
 *包名中的(.)用下划线(_)代替。参数中JNIEnv *是JNI环境，提供了许多方法。jobject是调用的java对象。
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
