/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIReference */

#ifndef _Included_TestJNIReference
#define _Included_TestJNIReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIReference
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_TestJNIReference_getIntegerObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     TestJNIReference
 * Method:    anotherGetIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_TestJNIReference_anotherGetIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
