/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIObjectArray */

#ifndef _Included_TestJNIObjectArray
#define _Included_TestJNIObjectArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIObjectArray
 * Method:    sumAndAverage
 * Signature: ([Ljava/lang/Integer;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_TestJNIObjectArray_sumAndAverage
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
